### ISSUE TITLE
Change the behaviour of restore

### ISSUE THREAD

**Issue by loongy** [talo/rush-py-legacy#35]
If `Restore=True` and there are 1 or more module instances with the same path and tags, then the SDK should use the latest module instance with the same paths and tags. Print a warning saying "WARNING - Detected existing job with the same paths and tags, re-using the latest job {id-here} instead of launch a new one" (or something similar). Ignore module instances that have a FAILED status.

If `Restore=False` ignore the above logic and just submit the module instance.

**Comment by s-i-l-k-e** [comment]
Closed in favour of new issue created
